=== Averlath/LM/CambridgeLevelExam/XML/DTD/xml.dtd
<?xml version="1.0" encoding="UTF-8"?>
  <!ELEMENT Questions (Question)+>
  <!ELEMENT Question (Title,Type,Answer*)>
  <!ELEMENT Title (#PCDATA)>
  <!ELEMENT Type (#PCDATA)>
  <!ELEMENT Answer (#PCDATA)>
  <!ATTLIST Answer correct CDATA #IMPLIED>
  <!ATTLIST Question id ID #REQUIRED>

=== Averlath/LM/CambridgeLevelExam/XML/DTD/xml.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Questions SYSTEM "xml.dtd">
<Questions>
  <Question id="t1">
  	<Title>(Where did I park the car?) I can't remember ... the car.</Title>
    <Type>Textfield</Type>
    <Answer>where I parked</Answer>
  </Question>
  <Question id="t2">
  	<Title>Very young children shouldn't go swimming by ....</Title>
    <Type>Textfield</Type>
    <Answer>themselves</Answer>
  </Question>
  <Question id="t3">
  	<Title>The river ... (flow) very quickly today, much faster than usual.</Title>
    <Type>Textfield</Type>
    <Answer>is flowing</Answer>
  </Question>
  <Question id="t4">
  	<Title>Call me after eight o'clock, we ... dinner by then. (finish)</Title>
    <Type>Textfield</Type>
    <Answer>will have finished</Answer>
  </Question>
  <Question id="t5">
  	<Title>Kevin'll do well in the job ... he stays on the right side of his boss.</Title>
    <Type>Textfield</Type>
    <Answer>as long as</Answer>
  </Question>


  <Question id="r1">
  	<Title>We were the only guests at the hotel.</Title>
    <Type>Radio</Type>
    <Answer>Nobody else had stayed there</Answer>
    <Answer correct="true">Nobody else was staying there</Answer>
    <Answer>Nobody else even stayed there</Answer>
    <Answer>Nobody else stayed there</Answer>
  </Question>
  <Question id="r2">
  	<Title>House prices are very high. They've ... a lot in the last few years.</Title>
    <Type>Radio</Type>
    <Answer>going up</Answer>
    <Answer>will go up</Answer>
    <Answer>will have gone up</Answer>
    <Answer correct="true">gone up</Answer>
  </Question>
  <Question id="r3">
  	<Title>There was so much traffic, I was lucky to get ... the road without being kocked over.</Title>
    <Type>Radio</Type>
    <Answer correct="true">Across</Answer>
    <Answer>Over</Answer>
    <Answer>Through</Answer>
    <Answer>Along</Answer>
  </Question>
  <Question id="r4">
  	<Title>The fresco is a dynamic work because, by capturing the energy, humanity, and collective achievement of the Detroit workers, celebrates all working men and women. (Which of the following alternatives is best to replace 'because'?)</Title>
    <Type>Radio</Type>
    <Answer>No change, leave it as it is.</Answer>
    <Answer>Replace it with: that was</Answer>
    <Answer>Replace it with: which</Answer>
    <Answer correct="true">Replace it with: that</Answer>
  </Question>
  <Question id="r5">
  	<Title>We talked just as easily as we had in the past, when we would sit in the field behind Joan’s house atop the rabbit hutch and discuss our friends and our hopes for the future. (Which of the following alternatives is best to replace 'in the field behind Joan’s house atop the rabbit hutch'?)</Title>
    <Type>Radio</Type>
    <Answer>No change, leave it as it is.</Answer>
    <Answer>Replace it with: in the field atop the rabbit hutch behind Joan’s house</Answer>
    <Answer>Replace it with: atop the rabbit hutch in the field behind Joan’s house</Answer>
    <Answer correct="true">Replace it with: behind Joan’s house in the field atop the rabbit hutch</Answer>
  </Question>


  <Question id="d1">
  	<Title>It's a great place to live apart from the increasing volume of ... that passes under my window every day.</Title>
    <Type>DropDown</Type>
    <Answer>Choose...</Answer>
    <Answer>transport</Answer>
    <Answer correct="true">traffic</Answer>
    <Answer>vehicles</Answer>
    <Answer>circulation</Answer>
  </Question>
  <Question id="d2">
  	<Title>I'm sorry, but he's already ....</Title>
    <Type>DropDown</Type>
    <Answer>Choose...</Answer>
    <Answer>made</Answer>
    <Answer>left</Answer>
    <Answer correct="true">gone</Answer>
    <Answer>had</Answer>
  </Question>
  <Question id="d3">
  	<Title>... harshly he may speak to you, you can be sure that he has only your best interests at heart.</Title>
    <Type>DropDown</Type>
    <Answer>Choose...</Answer>
    <Answer>Whereas</Answer>
    <Answer>Although</Answer>
    <Answer>Whether</Answer>
    <Answer correct="true">However</Answer>
  </Question>
  <Question id="d4">
  	<Title>The findings of the survey ... contrary to what was expected.</Title>
    <Type>DropDown</Type>
    <Answer>Choose...</Answer>
    <Answer>went</Answer>
    <Answer>made</Answer>
    <Answer>turned</Answer>
    <Answer correct="true">ran</Answer>
  </Question>
  <Question id="d5">
  	<Title>Local residents ... objected to the plans to build a supermarket where there is currently a beautiful park."></Title>
    <Type>DropDown</Type>
    <Answer>Choose...</Answer>
    <Answer correct="true">strenuously</Answer>
    <Answer>harshly</Answer>
    <Answer>roundly</Answer>
    <Answer>severely</Answer>
  </Question>


  <Question id="c1">
  	<Title>Later, in Rome, I was to meet Professor Taylor...</Title>
    <Type>Checkbox</Type>
    <Answer correct="true">but he had left before I got there.</Answer>
    <Answer>and was very impressed by his knowledge.</Answer>
    <Answer>but he was really nice.</Answer>
    <Answer correct="true">but he's gone now.</Answer>
  </Question>
  <Question id="c2">
  	<Title>Which word form of 'think' is not correct?</Title>
    <Type>Checkbox</Type>
    <Answer correct="true">taught</Answer>
    <Answer correct="true">though</Answer>
    <Answer>thought</Answer>
    <Answer>thinking</Answer>
  </Question>
  <Question id="c3">
  	<Title>I wouldn't do that ....</Title>
    <Type>Checkbox</Type>
    <Answer>so fastly</Answer>
    <Answer correct="true">without first reading the manual</Answer>
    <Answer correct="true">so quickly</Answer>
    <Answer correct="true">if I were you</Answer>
  </Question>
  <Question id="c4">
  	<Title>They didn't want to come with us at first, but we ... persuade them.</Title>
    <Type>Checkbox</Type>
    <Answer correct="true">managed to</Answer>
    <Answer>could</Answer>
    <Answer>didn't</Answer>
    <Answer correct="true">were able to</Answer>
  </Question>
  <Question id="c5">
  	<Title>Which sentences are correct?</Title>
    <Type>Checkbox</Type>
    <Answer>Problem with bureacracies is that they just grow and grow.</Answer>
    <Answer correct="true">They never shrink.</Answer>
    <Answer correct="true">Has anyone ever heard of a government who lowered taxes?</Answer>
    <Answer>And any government does get more efficient?</Answer>
  </Question>


  <Question id="m1">
  	<Title>Anna told me a very ... story.</Title>
    <Type>Cascade</Type>
    <Answer correct="true">interesting</Answer>
    <Answer>funnily</Answer>
    <Answer>sadly</Answer>
    <Answer>scarily</Answer>
  </Question>
  <Question id="m2">
  	<Title>Which word form of 'danger' is not correct?</Title>
    <Type>Cascade</Type>
    <Answer>dangerous</Answer>
    <Answer>dangerless</Answer>
    <Answer>endanger</Answer>
    <Answer correct="true">dangerfully</Answer>
  </Question>
  <Question id="m3">
  	<Title>I didn't expect the ground ... so much under my feet.</Title>
    <Type>Cascade</Type>
    <Answer>to moved</Answer>
    <Answer>to move</Answer>
    <Answer>to yield</Answer>
    <Answer correct="true">to give</Answer>
  </Question>
  <Question id="m4">
  	<Title>This time next week I won't be in the office. ... on a beach in Spain.</Title>
    <Type>Cascade</Type>
    <Answer>I'll</Answer>
    <Answer correct="true">I'll be lying</Answer>
    <Answer>I'm lying</Answer>
    <Answer>I'll have lain</Answer>
  </Question>
  <Question id="m5">
  	<Title>When we get to Thailand, ....</Title>
    <Type>Cascade</Type>
    <Answer>we'll be eating in restaurants again.</Answer>
    <Answer>you'll able to buy sandals like mine.</Answer>
    <Answer correct="true">we may have to hire a boat to take us out to the islands.</Answer>
    <Answer>we'll already have used up half your vacation.</Answer>
  </Question>
</Questions>
